CI: run coverage report and e2e tests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,26 +1,38 @@
-include:
-  - project: "famedly/company/frontend/ci-templates"
-    ref: main
-    file: "/all.yml"
-
-workflow:
-  rules:
-    - if: $CI_MERGE_REQUEST_IID
-    - if: $CI_COMMIT_TAG
-    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
-
 variables:
-  FLUTTER_IMAGE_TAG: "3.0.5"
+  FLUTTER_VERSION: "3.3.8"
+
+# update deps and format files
+.flutter_deps_and_format:
+  before_script:
+    - curl -s https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz | tar xfJ - -C /tmp
+    - export PATH="$PATH:/tmp/flutter/bin"
+    - sed -i "s#git@git.fairkom.net:#https://gitlab-ci-token:$CI_JOB_TOKEN@git.fairkom.net/#g" pubspec.yaml
+    - flutter pub get
+
+flutter_analyze:
+  extends:
+    - .flutter_deps_and_format
+  script: [flutter analyze --no-fatal-infos]
+
+lint:
+  extends:
+    - .flutter_deps_and_format
+  script:
+    - flutter pub run import_sorter:main --no-comments --exit-if-changed
+    - flutter format lib/ test/ --set-exit-if-changed
 
 coverage:
-  stage: test
-  image: registry.gitlab.com/famedly/company/frontend/flutter-dockerimages/flutter-linux/stable:${FLUTTER_IMAGE_TAG}
-  dependencies: []
+  tags: [docker]
   script:
-    - sed -i 's/#\([^ ]\)/\1/g' pubspec.yaml
-    - rm -r example
-    - ./scripts/prepare.sh
-    - ./scripts/test.sh
+    #TODO install olm?
+    - docker build -f docker/Dockerfile.coverage -t sdk-coverage --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA .
+    - docker create --name coverage sdk-coverage
+    - docker cp coverage:famedlysdk/coverage .
+    - docker cp coverage:famedlysdk/coverage.xml .
+    - docker cp coverage:famedlysdk/TEST-report.xml .
+    - docker cp coverage:/tmp/test.exitcode .
+    - docker rm coverage
+    - exit $(< test.exitcode)
   coverage: /^\s*lines\.*:\s*\d+.\d+\%/
   artifacts:
     when: always
@@ -34,89 +46,63 @@ coverage:
         path: coverage.xml
       junit: TEST-report.xml
 
-coverage_without_olm:
-  stage: test
-  image: dart
-  dependencies: []
-  variables:
-    NO_OLM: 1
-  before_script:
-    - apt-get update && apt-get install --no-install-recommends --no-install-suggests -y curl lcov python3 python3-distutils
-    - curl -o /bin/lcov_cobertura.py https://raw.githubusercontent.com/eriwen/lcov-to-cobertura-xml/master/lcov_cobertura/lcov_cobertura.py && sed 's/env python/env python3/' -i /bin/lcov_cobertura.py && chmod +x /bin/lcov_cobertura.py
-  script:
-    - dart pub get
-    - ./scripts/test.sh
-  #coverage: /^\s*lines\.*:\s*\d+.\d+\%/ <- broken see https://github.com/dart-lang/test/issues/1698
-  artifacts:
-    when: always
-    paths:
-      #- coverage/
-      #- coverage.xml
-      - TEST-report.xml
-    reports:
-      #coverage_report:
-      #  coverage_format: cobertura
-      #  path: coverage.xml
-      junit: TEST-report.xml
+#coverage_without_olm:
+#  stage: test
+#  image: dart
+#  dependencies: []
+#  variables:
+#    NO_OLM: 1
+#  before_script:
+#    - apt-get update && apt-get install --no-install-recommends --no-install-suggests -y curl lcov python3 python3-distutils
+#    - curl -o /bin/lcov_cobertura.py https://raw.githubusercontent.com/eriwen/lcov-to-cobertura-xml/master/lcov_cobertura/lcov_cobertura.py && sed 's/env python/env python3/' -i /bin/lcov_cobertura.py && chmod +x /bin/lcov_cobertura.py
+#  script:
+#    - dart pub get
+#    - ./scripts/test.sh
+#  #coverage: /^\s*lines\.*:\s*\d+.\d+\%/ <- broken see https://github.com/dart-lang/test/issues/1698
+#  artifacts:
+#    when: always
+#    paths:
+#      #- coverage/
+#      #- coverage.xml
+#      - TEST-report.xml
+#    reports:
+#      #coverage_report:
+#      #  coverage_format: cobertura
+#      #  path: coverage.xml
+#      junit: TEST-report.xml
 
 e2ee_test:
-  stage: test
-  image:
-    name: registry.gitlab.com/famedly/company/frontend/flutter-dockerimages/flutter/stable:${FLUTTER_IMAGE_TAG}
-    pull_policy: if-not-present
-  services:
-    - name: docker:dind
-      alias: docker
-  variables:
-    # activate container-to-container networking
-    FF_NETWORK_PER_BUILD: "true"
-    # Tell docker CLI how to talk to Docker daemon.
-    DOCKER_HOST: tcp://docker:2375/
-    # Use the overlayfs driver for improved performance.
-    DOCKER_DRIVER: overlay2
-    # Disable TLS since we're running inside local network.
-    DOCKER_TLS_CERTDIR: ""
-  dependencies: []
+  tags: [docker]
+    #  services:
+    #    - docker:dind
   parallel:
     matrix:
       - HOMESERVER:
-          - synapse
           - dendrite
-          - conduit
-  before_script:
-    - scripts/integration-prepare-alpine.sh
-    # create Synapse instance
-    - scripts/integration-server-$HOMESERVER.sh
-    # properly set the homeserver IP and create test users
-    - scripts/integration-prepare-homeserver.sh
-    # setup OLM
-    - scripts/prepare.sh
   script:
-    - ./scripts/test_driver.sh
+    - docker stop dendrite || true
+    - docker stop dockere2e || true
+    - docker stop dummy || true
+    - docker rm dendrite || true #not sure if the job deletes the container if the job fails
+    - docker rm dockere2e || true
+    - docker rm dummy || true
+    - docker volume rm dendrite || true
+    - docker build -f docker/Dockerfile.e2e -t docker-e2e --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA .
+    - docker volume create dendrite
+    - docker run --rm --entrypoint="" --volume=dendrite:/mnt:rw matrixdotorg/dendrite-monolith:latest /usr/bin/generate-keys -private-key /mnt/matrix_key.pem -tls-cert /mnt/server.crt -tls-key /mnt/server.key
+    - docker run --rm -d --volume=dendrite:/mnt --name dummy debian:bullseye-slim sh -c 'while ! test -e /mnt/dendrite.yaml;do sleep 2;done' #something's broken with docker, maybe docker:dind helps, but I'm unable to access the volume directory from the upper most container. So let's start a dummy container only for the purpose of copying the file...
+    - docker cp test_driver/dendrite/data/dendrite.yaml dummy:/mnt
+    - docker run -d --volume=dendrite:/etc/dendrite:rw --name dendrite -p 80:8008 matrixdotorg/dendrite-monolith:latest -really-enable-open-registration
+    - docker run -d --name dockere2e -t docker-e2e
+    - while [ -z $DENDRITE_IP ];do export DENDRITE_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' dendrite);sleep 2;done
+    - export DENDRITE_IP=$DENDRITE_IP:8008
+    - echo $DENDRITE_IP
+    - sed -i "s/notknownyet/$DENDRITE_IP/g" docker/e2e.entrypoint
+    - docker cp docker/e2e.entrypoint dockere2e:famedlysdk/entrypoint.sh
+    - docker exec -i dockere2e ./entrypoint.sh
+    - docker stop dendrite
+    - docker stop dockere2e
+    - docker rm dendrite
+    - docker rm dockere2e
+    - docker volume rm dendrite
   timeout: 10m
-
-dry-run:
-  stage: deploy
-  image: dart
-  script:
-    - dart pub get
-    - dart pub publish --dry-run
-
-pub-dev:
-  stage: deploy
-  image: dart
-  dependencies: [dry-run]
-  script:
-    - |
-      if [ -z "${PUB_DEV_CREDENTIALS}" ]; then
-        echo "Missing PUB_DEV_CREDENTIALS environment variable"
-        exit 1
-      fi
-
-      mkdir -p ~/.config/dart/
-      cp "${PUB_DEV_CREDENTIALS}" ~/.config/dart/pub-credentials.json
-
-    - dart pub get
-    - dart pub publish --force
-  rules:
-    - if: $CI_COMMIT_TAG
